name: ludvig
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - torchvision
  - open-clip-torch
  - jaxtyping
  - matplotlib
  - omegaconf
  - opencv
  - Pillow
  - plyfile
  - PyYAML
  - scikit-learn
  - scikit-image
  - scipy
  - tqdm
  - setuptools
  - pip
  - pip:
    # - pip install gaussiansplatting/submodules/diff-gaussian-rasterization --no-build-isolation
    # - pip install gaussiansplatting/submodules/simple-knn --no-build-isolation
    # - git+https://github.com/facebookresearch/segment-anything.git
    # - pip install git+https://github.com/facebookresearch/sam2.git
    # - pip install xformers --extra-index-url https://download.pytorch.org/whl/cu118 torch==2.6.0+cu118
